-- ============================================
-- 좋은습관PT 과제관리 - 보안 강화 배포용 스키마
-- ============================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS branches (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  color TEXT DEFAULT '#3B82F6',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS coaches (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'coach',
  emoji TEXT DEFAULT '🏋️',
  branch_id TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tasks (
  id TEXT PRIMARY KEY,
  branch_id TEXT,
  data JSONB NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = NOW(); RETURN NEW; END; $$ LANGUAGE plpgsql;
DROP TRIGGER IF EXISTS tasks_updated_at ON tasks;
CREATE TRIGGER tasks_updated_at BEFORE UPDATE ON tasks FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TABLE IF NOT EXISTS coach_credentials (
  coach_id TEXT PRIMARY KEY REFERENCES coaches(id) ON DELETE CASCADE,
  pin_hash TEXT NOT NULL,
  failed_attempts INTEGER DEFAULT 0,
  locked_until TIMESTAMPTZ,
  last_login_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
DROP TRIGGER IF EXISTS coach_credentials_updated_at ON coach_credentials;
CREATE TRIGGER coach_credentials_updated_at BEFORE UPDATE ON coach_credentials FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TABLE IF NOT EXISTS app_sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coach_id TEXT NOT NULL REFERENCES coaches(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  user_agent TEXT,
  expires_at TIMESTAMPTZ NOT NULL,
  revoked_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_app_sessions_token_hash ON app_sessions(token_hash);
CREATE INDEX IF NOT EXISTS idx_app_sessions_coach_id ON app_sessions(coach_id);

CREATE TABLE IF NOT EXISTS login_throttles (
  throttle_key TEXT PRIMARY KEY,
  failed_attempts INTEGER DEFAULT 0,
  locked_until TIMESTAMPTZ,
  last_attempt_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);
DROP TRIGGER IF EXISTS login_throttles_updated_at ON login_throttles;
CREATE TRIGGER login_throttles_updated_at BEFORE UPDATE ON login_throttles FOR EACH ROW EXECUTE FUNCTION update_updated_at();


CREATE TABLE IF NOT EXISTS push_subscriptions (
  endpoint TEXT PRIMARY KEY,
  coach_id TEXT REFERENCES coaches(id) ON DELETE CASCADE,
  coach_name TEXT,
  role TEXT DEFAULT 'coach',
  branch_id TEXT,
  subscription JSONB NOT NULL,
  preferences JSONB DEFAULT '{"urgentTask": true, "comment": true, "dueDigest": true, "dueDigestHour": 8}'::jsonb,
  user_agent TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ DEFAULT NOW()
);
DROP TRIGGER IF EXISTS push_subscriptions_updated_at ON push_subscriptions;
CREATE TRIGGER push_subscriptions_updated_at BEFORE UPDATE ON push_subscriptions FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE TABLE IF NOT EXISTS push_delivery_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind TEXT NOT NULL,
  dedupe_key TEXT UNIQUE NOT NULL,
  coach_id TEXT,
  endpoint TEXT,
  branch_id TEXT,
  meta JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 기존 pin_hash UNIQUE 제약 제거 (같은 4자리 PIN을 여러 코치가 사용할 수 있게 함)
ALTER TABLE coach_credentials DROP CONSTRAINT IF EXISTS coach_credentials_pin_hash_key;

-- 기존 평문 PIN을 bcrypt 해시로 1회 마이그레이션 (pin 컬럼이 남아있는 기존 DB 대응)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'coaches' AND column_name = 'pin'
  ) THEN
    INSERT INTO coach_credentials (coach_id, pin_hash)
    SELECT c.id, crypt(c.pin, gen_salt('bf'))
    FROM coaches c
    WHERE c.pin IS NOT NULL AND c.pin <> ''
      AND NOT EXISTS (SELECT 1 FROM coach_credentials cc WHERE cc.coach_id = c.id)
    ON CONFLICT (coach_id) DO NOTHING;

    ALTER TABLE coaches DROP COLUMN IF EXISTS pin;
  END IF;
END $$;

-- 참고: 이미 저장된 SHA-256 PIN 해시는 로그인 성공 시 서버에서 bcrypt 해시로 자동 업그레이드됩니다.

-- 초기 데이터 (배포용 기본 지점만 생성)
INSERT INTO branches (id, name, color)
VALUES ('branch-cheongra', '청라점', '#FF6B35')
ON CONFLICT (id) DO NOTHING;

-- 운영 계정/초기 PIN은 공개 저장소에 넣지 않는 것을 권장합니다.
-- 실제 배포 전에는 `seed-admin.template.sql`을 참고해 직접 관리자 계정을 생성하세요.

ALTER TABLE push_subscriptions
  ADD COLUMN IF NOT EXISTS preferences JSONB DEFAULT '{"urgentTask": true, "comment": true, "dueDigest": true, "dueDigestHour": 8}'::jsonb;

UPDATE push_subscriptions
SET preferences = jsonb_set(
  COALESCE(preferences, '{"urgentTask": true, "comment": true, "dueDigest": true, "dueDigestHour": 8}'::jsonb),
  '{dueDigestHour}',
  COALESCE(preferences->'dueDigestHour', '8'::jsonb),
  true
);

-- RLS: 브라우저 anon 접근 차단. 서버(service role)만 사용.
ALTER TABLE branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE coaches ENABLE ROW LEVEL SECURITY;
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE coach_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE push_delivery_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE login_throttles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS all_branches ON branches;
DROP POLICY IF EXISTS all_coaches ON coaches;
DROP POLICY IF EXISTS all_tasks ON tasks;
DROP POLICY IF EXISTS all_push_subscriptions ON push_subscriptions;
DROP POLICY IF EXISTS deny_all_branches ON branches;
DROP POLICY IF EXISTS deny_all_coaches ON coaches;
DROP POLICY IF EXISTS deny_all_tasks ON tasks;
DROP POLICY IF EXISTS deny_all_credentials ON coach_credentials;
DROP POLICY IF EXISTS deny_all_sessions ON app_sessions;
DROP POLICY IF EXISTS deny_all_push_subscriptions ON push_subscriptions;
DROP POLICY IF EXISTS deny_all_push_delivery_logs ON push_delivery_logs;
DROP POLICY IF EXISTS deny_all_login_throttles ON login_throttles;

CREATE POLICY deny_all_branches ON branches FOR ALL USING (false) WITH CHECK (false);
CREATE POLICY deny_all_coaches ON coaches FOR ALL USING (false) WITH CHECK (false);
CREATE POLICY deny_all_tasks ON tasks FOR ALL USING (false) WITH CHECK (false);
CREATE POLICY deny_all_credentials ON coach_credentials FOR ALL USING (false) WITH CHECK (false);
CREATE POLICY deny_all_sessions ON app_sessions FOR ALL USING (false) WITH CHECK (false);
CREATE POLICY deny_all_push_subscriptions ON push_subscriptions FOR ALL USING (false) WITH CHECK (false);
CREATE POLICY deny_all_push_delivery_logs ON push_delivery_logs FOR ALL USING (false) WITH CHECK (false);
CREATE POLICY deny_all_login_throttles ON login_throttles FOR ALL USING (false) WITH CHECK (false);
